site_name: My Project
theme: material
nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
            docstring_style: google
